service: <%= name %>
provider:
  name: aws
  region: <%= region %>
  runtime: nodejs6.10
  stage: develop
  environment: '${file(.env.yml):${self:custom.stage}}'
custom:
  stage: "${opt:stage, self:provider.stage}"
package:
  include:
    - node_modules/**
  exclude:
    - .env.yml
    - .env.yml.example
    - templates/**
functions:
  get-dummy:
    name: get-dummy
    description: Get dummy method description
    handler: functions/dummy/get.handler
    events:
      - http:
          method: GET
          path: dummy
          cors: true
  post-dummy:
    name: post-dummy
    description: Post dummy method description
    handler: functions/dummy/post.handler
    events:
      - http: POST dummy
  put-dummy:
    name: put-dummy
    description: Put dummy method description
    handler: functions/dummy/put.handler
    events:
      - http: PUT dummy
  delete-dummy:
    name: delete-dummy
    description: Delete dummy method description
    handler: functions/dummy/delete.handler
    events:
      - http: DELETE dummy
resources:
  Resources:
    ApiGatewayRestApi:
      Type: 'AWS::ApiGateway::RestApi'
      Properties:
        Name: 'Serverless RESTful API (${self:custom.stage})'
